name: Send GET API Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (UTC)
  workflow_dispatch:        # Optional: allows manual trigger

jobs:
  send-get-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request
        run: |
          curl -X GET "https://x-store-w2wn.onrender.com/"
